services:
  - type: web
    name: opinion-mining-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn opinion_mining.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 